name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build
      run: go build -v ./...
    - name: check files
      run: ls
    - name: Test
      run: go test -v ./...
    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BuildOutput
        path: artifact.zip
