name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  WORKFLOW_ENV: workflow_env_value
jobs:
  build:
    env:
      JOB_ENV1: job_env1_value
      JOB_ENV2: job_env2_value
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.19', '1.20', '1.21.x']
    steps:
    - uses: actions/checkout@v4
    - name: Get dependencies
      uses: actions/cache@v4
      with:
        path:  |
          ~/go/pkg/mod # actually uses `go env GOMODCACHE` output
          ~/.cache/go-build # actually uses `go env GOCACHE` output        
        key: deps-go-${{ hashFiles('go.sum') }}
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Build
      run: go build -v ./...
    - name: check files
      run: ls -al
    - name: Test
      run: go test -v ./...
    - name: output env values
      run: |
        echo "workflow env value is $WORKFLOW_ENV"
        echo "job env1 value is ${{ env.JOB_ENV1 }} & job env2 is $JOB_ENV2"
    # - name: Artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: BuildOutput
    #     path: ~/
