name: Go

on:
  push:
    branches:
      - master
      - dev
  # pull_request:
  #   branches: [ "master" ]
env:
  WORKFLOW_ENV: ${{ secrets.WORKFLOW_ENV }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get dependencies
      uses: actions/cache@v4
      with:
        path:  |
          ~/go/pkg/mod # actually uses `go env GOMODCACHE` output
          ~/.cache/go-build # actually uses `go env GOCACHE` output        
        key: deps-go-${{ hashFiles('go.sum') }}
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
    - name: Run linting for Go
      run: |
        go install golang.org/x/lint/golint@latest
        set -e
        echo "See below linting"
        golint ./...
        
  build:
    environment: test
    env:
      JOB_ENV1: ${{ secrets.JOB_ENV1 }}
      JOB_ENV2: job_env2_value
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21.x']
    steps:
    - uses: actions/checkout@v4
    - name: Get dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path:  |
          ~/go/pkg/mod # actually uses `go env GOMODCACHE` output
          ~/.cache/go-build # actually uses `go env GOCACHE` output        
        key: deps-go-${{ hashFiles('go.sum') }}
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Build
      if: steps.cache.outputs.cache-hit != 'true'
      run: go build -v ./...
    - name: check files
      run: |
        tree -d .
        ls -al
    - name: Test
      if: steps.cache.outputs.cache-hit != 'true'
      run: go test -v ./...
    - name: output env values
      run: |
        echo "workflow env value is $WORKFLOW_ENV"
        echo "job env1 value is ${{ env.JOB_ENV1 }} & job env2 is $JOB_ENV2"
    - name: Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BuildOutput
        path: ./
  
  test:
    needs: build
    uses: ./.github/workflows/go.yml
    
  status:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: overall status
        if: failure()
        run: |
          echo "Check the other jobs status"
          echo "${{ toJson(github) }}
        
