# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Golang GitHub CI

on: workflow_call
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: BuildOutput
      - name: Output contents
        run: ls -alR
      - name: Deployment
        run: echo "Deploying..."
